/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWatchRouteImport } from './routes/_app/watch'
import { Route as AppWalletRouteImport } from './routes/_app/wallet'
import { Route as AppReelsRouteImport } from './routes/_app/reels'
import { Route as AppPartnersRouteImport } from './routes/_app/partners'
import { Route as AppMineRouteImport } from './routes/_app/mine'
import { Route as AppFeedRouteImport } from './routes/_app/feed'
import { Route as AppChatRouteImport } from './routes/_app/chat'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWatchRoute = AppWatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => AppRoute,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRoute,
} as any)
const AppReelsRoute = AppReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => AppRoute,
} as any)
const AppPartnersRoute = AppPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AppRoute,
} as any)
const AppMineRoute = AppMineRouteImport.update({
  id: '/mine',
  path: '/mine',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedRoute = AppFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof AppChatRoute
  '/feed': typeof AppFeedRoute
  '/mine': typeof AppMineRoute
  '/partners': typeof AppPartnersRoute
  '/reels': typeof AppReelsRoute
  '/wallet': typeof AppWalletRoute
  '/watch': typeof AppWatchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof AppChatRoute
  '/feed': typeof AppFeedRoute
  '/mine': typeof AppMineRoute
  '/partners': typeof AppPartnersRoute
  '/reels': typeof AppReelsRoute
  '/wallet': typeof AppWalletRoute
  '/watch': typeof AppWatchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/feed': typeof AppFeedRoute
  '/_app/mine': typeof AppMineRoute
  '/_app/partners': typeof AppPartnersRoute
  '/_app/reels': typeof AppReelsRoute
  '/_app/wallet': typeof AppWalletRoute
  '/_app/watch': typeof AppWatchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chat'
    | '/feed'
    | '/mine'
    | '/partners'
    | '/reels'
    | '/wallet'
    | '/watch'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/chat'
    | '/feed'
    | '/mine'
    | '/partners'
    | '/reels'
    | '/wallet'
    | '/watch'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/chat'
    | '/_app/feed'
    | '/_app/mine'
    | '/_app/partners'
    | '/_app/reels'
    | '/_app/wallet'
    | '/_app/watch'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/watch': {
      id: '/_app/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof AppWatchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wallet': {
      id: '/_app/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reels': {
      id: '/_app/reels'
      path: '/reels'
      fullPath: '/reels'
      preLoaderRoute: typeof AppReelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/partners': {
      id: '/_app/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof AppPartnersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mine': {
      id: '/_app/mine'
      path: '/mine'
      fullPath: '/mine'
      preLoaderRoute: typeof AppMineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feed': {
      id: '/_app/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AppFeedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppChatRoute: typeof AppChatRoute
  AppFeedRoute: typeof AppFeedRoute
  AppMineRoute: typeof AppMineRoute
  AppPartnersRoute: typeof AppPartnersRoute
  AppReelsRoute: typeof AppReelsRoute
  AppWalletRoute: typeof AppWalletRoute
  AppWatchRoute: typeof AppWatchRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChatRoute: AppChatRoute,
  AppFeedRoute: AppFeedRoute,
  AppMineRoute: AppMineRoute,
  AppPartnersRoute: AppPartnersRoute,
  AppReelsRoute: AppReelsRoute,
  AppWalletRoute: AppWalletRoute,
  AppWatchRoute: AppWatchRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
